"""add new rows

Revision ID: 0f76fd142db7
Revises: 24b64f19f6df
Create Date: 2026-02-02 00:02:43.111202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f76fd142db7'
down_revision: Union[str, Sequence[str], None] = '24b64f19f6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'users',
    sa.Column(
        'provider',
        sa.String(),
        nullable=False,
        server_default='local'
    )
)

    op.add_column('users', sa.Column('provider_id', sa.String(), nullable=False, server_default='local'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'provider')
    # ### end Alembic commands ###
