"""add task table

Revision ID: 1b244f76c8dc
Revises: 0f76fd142db7
Create Date: 2026-02-04 00:38:55.346854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b244f76c8dc'
down_revision: Union[str, Sequence[str], None] = '0f76fd142db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'local'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'local'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_table('tasks')
    # ### end Alembic commands ###
